### ISSUE TITLE
Formant track analysis cannot find subset

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/SPADE#42] opened 2019-07-10 21:14 UTC
I'm testing the `formant_track.py` script on ICE-Can, where a subset is supposed to be made for the class of unisyn vowels. When I run this however, I get the following error:
```
Traceback (most recent call last):
  File "formant_track.py", line 121, in <module>
    corpus_conf['speakers'], vowel_prototypes_path = vowel_prototypes_path)
  File "formant_track.py", line 37, in formant_track_export
    common.formant_acoustic_analysis(config, None, vowel_prototypes_path, drop_formant = drop_formant, output_tracks = True, subset="unisyn_subset")
  File "/home/linguistics/jtanner/SPADE/Common/common.py", line 310, in formant_acoustic_analysis
    output_tracks = output_tracks
  File "/data/iscan-spade-server/src/polyglotdb/polyglotdb/acoustics/formants/refined.py", line 72, in analyze_formant_points_refinement
    raise Exception('Phones do not have a "{}" subset.'.format(vowel_label))
Exception: Phones do not have a "unisyn_subset" subset.
```
@mmcauliffe suggested that this would have something to do with the version of polyglot on Oka, but it looks like it's correct, and so I have no idea why it's failing here.

**Comment by msonderegger** [comment] 2019-07-11 09:33
Does the (exact) same script work without error on roquefort?  Testing this helps diagnose whether the issue is oka-specific.

**Comment by mmcauliffe** [comment] 2019-07-11 14:17
This has been fixed on the formant track branch of master.  The main issue being that the formant encoding function creates a new CorpusContext scope that was inside a larger CorpusContext scope that was doing the vowel subset and then the query.  I've broken it out to be more serial, so there shouldn't be any persistence of old CorpusContext objects that don't have the correct meta information about what's been encoded.

**Closed by mmcauliffe** 2019-07-11 14:17 UTC
